[package]
name = "docrlib"
version = "0.3.0"
authors = ["mush42 <musharraf.omer@gmail.com>"]
edition = "2024"

[lib]
name = "docrlib"
crate-type = ["cdylib"]

[dependencies]
docrapi = { path = "../docrapi" }
libc = "0.2.173"
serde = "1.0.219"
serde_json = "1.0.140"
widestring = "0.4.3"
