[package]
name = "docrlib"
version = "0.2.0"
authors = ["mush42 <musharraf.omer@gmail.com>"]
edition = "2021"

[lib]
name = "docrlib"
crate-type = ["cdylib"]

[dependencies]
docrapi = { path = "../docrapi" }
libc = "0.2.158"
serde = "1.0.210"
serde_json = "1.0.128"
widestring = "0.4.3"
