[package]
name = "docrpy"
version = "0.2.0"
authors = ["mush42 <musharraf.omer@gmail.com>"]
edition = "2021"

[dependencies]
docrapi = { path = "../docrapi" }

[lib]
name = "docrpy"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.16.6"
features = ["extension-module"]
